### ISSUE TITLE
i can't edit with user "dev"

### ISSUE THREAD

**Issue by zorrochen** [michele-bertasi/go-docker-dev#4]
sorry for my poor english, need your more patience。thanks.

for some network reason, i try to build my vim-go failed。 your docker images is nice，i used it, and it run success.

but when i mount my direction to docker,  “root” is inside，and i can't edit with user "dev".

how i can solve it, need your help, thanks again.

**Comment by mbrt** [comment]
I'm not sure it's a networking problem. Is it the build or the run that fails?
I suggest you to use a reasonably new Docker version (`docker --version`), and try to run the image with:
```
docker run [other options] -u dev [image] [command]
```
so you set the user explicitly. You can also test if the user is there by looking at `grep dev /etc/passwd`.

**Comment by zorrochen** [comment]
@mbrt, thank you for answer.

in my country, for government reasons, network is restricted. when i config my vim, "PluginIntall" not run as expect.

so when i found your docker image, it seems fit me.

your answer give me inspiration，i use command like this, and it worked！root can solve everything.
> docker run [other options] -u **root** [image]  [command]

it's my first github issue, a nice experience. thank you for your patience, wish you a happy life.
