### ISSUE TITLE
Docker Build fails with: Error detected while processing function... Can't open file...  

### ISSUE THREAD

**Issue by WhisperingChaos** [michele-bertasi/go-docker-dev#5]
When running ```docker build``` the following messages are produced during the ```#install vim plugins``` step located in the ```Dockerfile```:
```
Error detected while processing function plug#end:
line 83:
E484: Can't open file /usr/share/vim/vim80/syntax/syntax.vim
Error detected while processing /home/dev/.vimrc: 
line21:
E484: Can't open file /usr/share/vim/vim80/syntax/syntax.vim
Press ENTER or type command to continue
```
Traced cause to:
```
make VIMRUNTIMEDIR=/usr/share/vim/vim80
```
I think it directs the ```PlugInstall``` program to the directory containing the desired plugins.  Seems _github.com/vim/vim.git_ repository has changed the ```/usr/share/vim/vim80``` to ```/usr/share/vim/vim81```.  Updated my clone repository version to reflect ```vim81``` which successfully installed the plugins completing the image build.

BTW been using the Docker Hub image for years as my golang IDE - it's wonderful!  Working on a project that requires repeatable construction of development tools, therefore, cloned your project and will be "inserting" build arguments to direct installation of specific dependent component versions.

**Comment by mbrt** [comment]
Thanks for reporting! I'm glad the image was useful!
Fixed as suggested in 164e126402e1e72fea012b08c132b6e289720f96.
