### ISSUE TITLE
UI block, stuck, unresponsive, with message:  vim-go: initializing gopls

### ISSUE THREAD

**Issue by WhisperingChaos** [michele-bertasi/go-docker-dev#8]
vim UI becomes forever unresponsive after displaying message ```vim-go: initializing gopls```.  Happens, for example, when undoing edits.  See related [vim-go #2414](https://github.com/fatih/vim-go/issues/2414#issuecomment-570760248) for discussion and potential solution.

**vim-go version:**
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 28 2019 20:36:17)
Included patches: 1-2424
```

**go version:**  ```go version go1.13.5 linux/amd64```

This might not be an issue with go-docker-dev, as it's Dockerfile is crafted to obtain the latest components.  vim-go 8.2 may include installing ```gopls```.  I happened to encounter it because I wanted to use the newest golang version but maintain using vim-go 8.1, so I altered the Dockerfile by adding build ARGs.

Also, this issue isn't expressing itself when running the current image from docker hub because it hasn't been build recently and reflects the following:

**vim-go version:**
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 25 2018 18:32:51)
Included patches: 1-635
```

**go version:**  ```version go1.11.4 linux/amd64```

Which don't rely on [LSP](https://langserver.org/) support.

If for some reason the current vim-go 8.2 release doesn't install ```gopls```, it's a one line fix to the current Dockerfile:

```
RUN go get golang.org/x/tools/cmd/godoc                                 && \
    go get github.com/nsf/gocode                                        && \
    go get golang.org/x/tools/cmd/goimports                             && \
    go get github.com/rogpeppe/godef                                    && \
    go get golang.org/x/tools/cmd/gorename                              && \
    go get golang.org/x/lint/golint                                     && \
    go get github.com/kisielk/errcheck                                  && \
    go get github.com/jstemmer/gotags                                   && \
    go get github.com/tools/godep                                       && \
>   GO111MODULE=on go get golang.org/x/tools/gopls@latest               && \
    mv /go/bin/* /usr/local/go/bin                                      && \

```

**Comment by mbrt** [comment]
Thanks for the detailed report!

Adding `gopls` by default shouldn't hurt even if the problem you describe doesn't happen yet, so I'll go ahead and just add your workaround.
